apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  namespace: argocd
spec:
  destination:
    namespace: demoapp
    server: 'https://kubernetes.default.svc'
  source:
    path: charts
    repoURL: 'https://github.com/IshwarKhadka000/Php-Guestbook.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true